version: '3'
services:
  api-produtosdb:
    image: postgres:latest
    container_name: api-posts
    environment:
      POSTGRES_DB: apipostsdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
